name: "Build and push to ECR"

on: 
  push: 
    branches: [ "main" ]
jobs:
  BuildAndPushImageToECR:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Make the script files executable
        run: chmod +x app/scripts-main/job.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA6FXGX4FDHDC4UD6P
          aws-secret-access-key: i+t+eX5DITTTNcErn5cNXkjC0g8AZyivuWTqWGdK
          aws-session-token: IQoJb3JpZ2luX2VjEIX//////////wEaCXVzLWVhc3QtMiJHMEUCIDOOGkaLVjE7hCCqR8POdLACZPjNtkVYc2ipx1B118/QAiEA0r936iXhxEXt8sKzGFT0PXQcMcD09Qfyp/TMQ4L5eLIqgwMIfhADGgw5NzQzNjc3NDQzMjYiDPrS1d7BaMVoNJSvLirgAg9XNUDe9Z3Aic4OqpZuTTlUWA94+0eTUqjPOE/qtl0J15FRQHQTbjy0BGGg9FxqLMwtlk4edfi4NvrUL4AyRBypbH+p7z3lxXbk1j3Rgo3VXdDol2+beldcpaUjVSPdLH/c6ZuI0CSlImEdV8LjWGX1vuOOeCZDUmy5413Hao61xswzkakJnXfnGm6KTnf1QKyX2APZWLEIaKp11OtTim7ttKdmvxLzuLDN7EwZxRBloqXvxxohHnmIDOyFr37ZPbHKKaGPb8hhGoXvRwV2bdswgZ84KQBI/PVmpvsuAH+UGHq0rx8v7rwTLBG1eodys7x6VJuRg9OEhU+jeF11JwOy7tn+uwmkZiIJbSc/zyq9Dn8ypH/KwuxYVIE1iKs9Nn9snUeZ3BZnJXRcU10SDuH5CaGL2UNxza0PajqjGFUChpwf6Kr/Ck4Law21u2weKCsNCETS3VRzu9ciz7eSnbYwqJXNqAY6pgHmdbjpnsdgoLNGWiZ15a679lp7nMwNyNCONDJCPTRwHnICR76jEBdx1Y+eMTaaCV9xNJdU76r0gzof89kFyGW9zBiZgX0NtvOgR7M+e3Vx2kEMtSiW/P//OUXdQub6FZMiOLnwwoBsuaymen66huLiiMEzzs1Tj6nNh6QyD97omj9iQ//O0bIkbVirVUr+ao9PAUqjy4aG8T/mEyVMbj/nMef9pfWe
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "rhone_glacier"
          IMAGE_TAG: v1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
